const router = require("express").Router()

const adminRouter = require("./admin.route")
const adminAuth = require("./admin_auth.route")
const userRouter = require("./user.route")
const userAuth = require("./user_auth.route")
const workerAuth = require("./worker_auth.route")
const workerRouter = require("./worker.route")
const companyRouter = require("./company.route")
const serviceRouter = require("./serivice.route")
const workerServiceRouter = require("./worker_service.route")
const companyServiceRouter = require("./company_service.route")
const contractRouter = require("./contract.route")
const paymentRouter = require("./payment.route")
const workerWorkTimeRouter = require("./workerTime.route")
const companyWR = require("./companyWT.route")
const sorovlar = require("./sorovlar.route")


router.use("/admin", adminRouter)
router.use("/Aauth", adminAuth)
router.use("/user", userRouter)
router.use("/Uauth", userAuth)
router.use("/Wauth", workerAuth)
router.use("/worker", workerRouter)
router.use("/company", companyRouter)
router.use("/service", serviceRouter)
router.use("/workerService", workerServiceRouter)
router.use("/companyService", companyServiceRouter)
router.use("/contract", contractRouter)
router.use("/payment", paymentRouter)
router.use("/workerWorkT", workerWorkTimeRouter)
router.use("/companyWT", companyWR)
router.use("/sorovlar", sorovlar)

module.exports = router